sources:
  youtube_videos: []
      
  blog_posts:
    - url: "data:text/html,<html><body><h1>Test Blog Post</h1><p>Check out this <a href='https://amazon.co.uk/dp/B08N5WRWNW'>great product on Amazon</a> and this <a href='https://www.aliexpress.com/item/1005001234567890.html'>item on AliExpress</a></p></body></html>"
      title: "Test Blog Post with Links"

settings:
  concurrent_requests: 2
  request_timeout: 30
  retry_attempts: 2
  delay_between_requests: 0.5
  youtube_api_key: null